name: Check Gradle-based Projects
on: pull_request

jobs:
  java17:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: 'jdk+fx'
      - run: |-
          cd Gradle/Compose
          ./gradlew build
          cd ../Gradle/Console
          ./gradlew build
          cd ../JavaFX
          ./gradlew build
          cd ../Swing
          ./gradlew build
          cd ../SWT
          ./gradlew build
