name: Check Gradle-based Projects
on: pull_request

jobs:
  java8:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
      - run: |-
          cd Gradle/Core
          ./gradlew build
          cd ../JavaFX
          ./gradlew build
          cd ../Swing
          ./gradlew build
          cd ../SWT
          ./gradlew build

  java11:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - run: |-
          cd Gradle/JavaFX-11
          ./gradlew build
